
version: '3.8'
services:
  web:
    image: candycbt:latest
    container_name: candycbt
    ports:
    - 8033:80
    volumes:
      - ./app:/var/www/html:rw
    networks:
    - candynet
    environment:
    restart: unless-stopped
   

  db:
    container_name: mariadb
    restart: unless-stopped
    image: mariadb:10.4.33
    environment:
      - MARIADB_ROOT_PASSWORD: Cpu25
      - MARIADB_USER: dbuser
      - MARIADB_PASSWORD: strongpw
      - MARIADB_DATABASE: candydb
    volumes:
      - ./data:/var/lib/mysql:rw
    networks:
      - candynet


networks:
  candynet:
    driver: bridge