
version: '3.8'
services:
  web:
    # image: wisnuflash/candymod:latest
    image: porchn/php7-apache
    #build: .
    container_name: candycbt
    ports:
    - 8033:80
    - 8022:8022
    - 8023:8023
    volumes:
      # - app-candycbt:/var/www/html:rw
      - ./app/ma:/var/www/html:rw
      - ./app/mts:/var/www/mts:rw
      - ./app/smk:/var/www/smk:rw
      - ./config/apache:/etc/apache2/sites-enabled:rw
      - ./config/php.ini:/usr/local/etc/php/php.ini:rw
    networks:
    - candynet
    environment: 
     TZ: Asia/Jakarta
     DB_HOST: mariadb
     DB_USER: root
     DB_PASS: Cpu25
     DB_NAME: candynew
    restart: unless-stopped
    depends_on:
      - db 
   

  db:
    container_name: mariadb
    restart: unless-stopped
    image: mariadb:10.4.33
    environment:
      MARIADB_ROOT_PASSWORD: Cpu25
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: strongpw
      MARIADB_DATABASE: candydb
    volumes:
      # - ./data:/var/lib/mysql:rw
      - mariadb-data:/var/lib/mysql:rw
    networks:
      - candynet

volumes:
  mariadb-data: {}
  app-candycbt: {}
networks:
  candynet:
    driver: bridge